import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GPT Ads",
  description: "Generated by create next app",
};

declare global {
  interface Window {
    googletag: any
  }
  const googletag: any
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: "window.googletag = window.googletag || {cmd: [] };" }} />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
